[project]
name = "hexlet-code"
version = "0.1.0"
description = "Task management system"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.8",
    "django-bootstrap5>=25.3",
    "gunicorn>=23.0.0",
]
